name: test
inputs:
  input1:
    description: first input
    required: false
    type: string
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: aqeel1211/test-conditions
        ref: main
    - name: test condition
      run: |
        if [ ${{ inputs.input1 }} ] == ''; then
          echo "input1 is empty"
        fi
      shell: bash
