name: test
inputs:
  input1:
    description: first input
    required: false
    type: string
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: aqeel1211/test-conditions
        ref: main
    - name: Check input presence
      id: checksecrets
      shell: bash
      run: |
        if [ -z ${{ inputs.input1 }} ]; then
          echo "secretspresent=NO" >> $GITHUB_OUTPUT
        else
          echo "secretspresent=YES" >> $GITHUB_OUTPUT
        fi
    - name: run step if secret is present
      if: (steps.checksecrets.outputs.secretspresent == 'NO')
      run: echo "input is empty"
#     - name: test condition
#       run: |
#         if [ -z ${{ inputs.input1 }} ]; then
#           echo "input1 is empty"
#         fi
      shell: bash
